version: '3'
services:
  proxy:
    image: nginxplus
    hostname: proxy
    ports:
      - "8883:8883"
      - "1883:1883"
      - "80:80"
    volumes:
      - ./njs:/etc/nginx/njs:ro
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
      - ./stream.conf.d:/etc/nginx/stream.conf.d:ro
      - ./mtls:/mtls
    command: sh -c "/mtls/certs.sh && nginx -g 'daemon off;'"
  broker:
    image: emqx/emqx
    hostname: broker
    #scale: 2  # Remove ports: when using scale
    ports:
      - "18083:18083"

